diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
index d1482ef..837c183 100644
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -17,12 +17,15 @@ jobs:
         - 'Django>=3.0,<3.1'
         - 'Django>=3.1,<3.2'
         - 'Django>=3.2,<3.3'
-        - 'https://github.com/django/django/archive/refs/heads/main.zip#egg=Django'
         experimental: [false]
         include:
+        - python: '3.10'
         - django: 'https://github.com/django/django/archive/refs/heads/main.zip#egg=Django'
           experimental: true
-    continue-on-error: ${{ matrix.experimental }}
+          # NOTE this job will appear to pass even when it fails because of
+          # `continue-on-error: true`. Github Actions apparently does not
+          # have this feature, similar to Travis' allow-failure, yet.
+          # https://github.com/actions/toolkit/issues/399
     services:
       postgres:
         image: postgres:latest
@@ -56,5 +59,6 @@ jobs:
             "PORT":"5432"
           }
       run: nosetests
+      continue-on-error: ${{ matrix.experimental }}
     - name: check style
       run: flake8 django_cte/ tests/
